services:
  node:
    image: node:20
    container_name: node-container
    volumes:
      - /home/rimedelis/code:/code
      - /var/run/docker.sock:/var/run/docker.sock  # Expose the host Docker socket
    working_dir: /code
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "
        apt-get update && \
        apt-get install -y build-essential curl git libsodium23 docker.io && \
        rm -f /usr/local/bin/yarn /usr/local/bin/yarnpkg && \
        npm install -g yarn && \
        tail -f /dev/null
      "
    ports:
      - "3000:3000"
      - "5173:5173"
      - "5174:5174"
      - "5175:5175"
    restart: unless-stopped
    networks:
      - default

  composer:
    image: composer:latest
    container_name: composer-container
    volumes:
      - /home/rimedelis/code:/code
    working_dir: /code
    environment:
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - "8000:8000"
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && tail -f /dev/null"
    restart: unless-stopped
    networks:
      - default

  python:
    image: python:3.11
    container_name: python-container
    volumes:
      - /home/rimedelis/code:/code
    working_dir: /code
    environment:
      - DEBIAN_FRONTEND=noninteractive
    network_mode: host
    privileged: true
    command: >
      bash -c "
        apt-get update && \
        apt-get install -y python3-pip python3-dev tshark && \
        pip install pyshark python-dotenv python-telegram-bot requests beautifulsoup4 && \
        tail -f /dev/null
      "
    ports:
      - '5000:5000'
    restart: unless-stopped

networks:
  default:
    driver: bridge
